### ISSUE TITLE
Incorrect settings

### ISSUE THREAD

**Issue by LisaE14** [juacas/quizaccess_activatedelayedattempt#14]
If our teachers set the quiz time i.e. from 9-10 am and time limit 60 minutes, then the students have random less than 60 minutes with this plug-in. 

It would be great if the time limit must be set and if there is a warning, when the difference between quiz duration and time limit ist lower than the maximum delay.

**Comment by juacas** [comment]
Did you activate the warnings for the teachers? (Shows the teacher a warning if their quiz is resource intensive
quizaccess_delayed | showdangerousquiznotice) It is in the general settings ( Site administration -> Plugins -> Activity modules -> Quiz  -> Entry to quiz attempt with random delay  url: /admin/settings.php?section=modsettingsquizcatdelayed)

With the settings you described you should view:

![Screenshot - 10_08_2020 , 11_37_21](https://user-images.githubusercontent.com/1656180/89770039-76543580-dafe-11ea-9310-57e1095b3990.png)

With the blue message always showing and the orange one only shown if you activate that option.

Please check it and let me know if it was the reason.

**Comment by LisaE14** [comment]
No, i thought this warnings are just for short pages ;-)
So this warning would be good even if it is only displayed to teachers when they click on "save and display". It would be great if you could make 2 settings - 1 for each warning. Because we do not want a warning for short pages. We advise one question per page.

**Comment by juacas** [comment]
Hi, the problem this plugin tries to fight is mostly related to the frequency of "clicks" that the students do during the tests. The most clicks (page submission) the more load on the server and the higher the risk of DoS.
Hence, the problem is not with the number of questions on each page but with the average time of each page.
In my experience, if you phase the entry to the quiz but forces the students to submit a lot of pages during the quiz the server will suffer high loads anyway, i.e. the plugin will not helps a lot.

By the mean time, to meet your requirements, I suggest to edit locally the language strings in your server and empty the key "tooshortpagesadvice".  This way no message will show. (You can find it at url https://[Your server]/admin/tool/customlang/index.php)
