### ISSUE TITLE
How is this different from quizaccess_activateattempt?

### ISSUE THREAD

**Issue by mudrd8mz** [juacas/quizaccess_activatedelayedattempt#3]
There is an existing plugin https://moodle.org/plugins/quizaccess_activateattempt that seems to aim the same use case. How is your solution different from the existing one? (I am aware of the recent reports that claim it does not work well).

**Comment by juacas** [comment]
Basically, this plugin was developed and deployed urgently due to covid19. The other plugin was unattended some time long.
The functionality currently differs in almost everything but the basic idea
- delay is not only larger but dynamic and randomised by user.
- random delay calculated by heuristics.
- per-activity enablement
- animated countdown
- teacher feedback about problematic configuration based on heuristics.
- parameter customisation such as entry rate, maximum delays, delay relative to time limit.
- student's institutional notice.
- more to come (active development)
PD: by the way, what are those problems you mention?

**Comment by juacas** [comment]
Of course, original authors are credited in the doc sections.

**Comment by mudrd8mz** [comment]
OK, thank you for the details. That helps.

> by the way, what are those problems you mention?

Recent comments at https://moodle.org/plugins/quizaccess_activateattempt suggest it did not work well for some, and there does not seem to be any update from the authors.
